import {TrialConnection} from './connection.js?v=demo-v0.02';
const $=id=>document.getElementById(id),storageKey='mt-trial-v03-session';let session='',remaining=0,ready=false,pending=false,acting=false,recognition=null,recognizing=false;
const sceneReady=window.GameView?Promise.resolve():new Promise(resolve=>document.addEventListener('scene-ready',resolve,{once:true}));
const report=(text,error=false)=>{$('feedback').textContent=text;$('feedback').parentElement.classList.toggle('error',error);};
function updateControls(){const locked=pending||acting;$('send').disabled=locked||!ready||remaining<=0;$('input').disabled=pending;$('reset').disabled=locked||!ready;$('voice').disabled=pending||!recognition;document.querySelectorAll('[data-prompt]').forEach(b=>b.disabled=pending);}
async function post(url,body){const res=await TrialConnection.fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(Number.isInteger(data.remaining))remaining=data.remaining;if(!res.ok){const error=Error(data.error||'这一轮未完成。');error.status=res.status;throw error;}return data;}
function remember(id){try{localStorage.setItem(storageKey,id);}catch{$('saveStatus').textContent='浏览器未允许保存会话编号，刷新后需重新进入。';}}
const labels={undecided:'尚未决定留下或迁徙',security:'已签下治安军申请',resistance_contact:'正在试探隐蔽联系',migration:'与同行者一起进入强制转运队列'};
function showState(state){$('route').textContent=labels[state.route]||labels.undecided;window.__gameState=state;}
async function connect(){await sceneReady;ready=false;updateControls();
try{const reply=await TrialConnection.fetch('/api/health',{cache:'no-store'});const health=await reply.json();if(!reply.ok)throw Error(health.error||'试玩连接未完成。');remaining=health.remaining;const serviceReady=health.ready;let saved='';try{saved=localStorage.getItem(storageKey)||'';}catch{}
 let current;try{current=await post('/api/session',saved?{id:saved}:{});}catch(error){if(!saved||error.status!==409)throw error;report('旧存档未找到，已进入新的局面。');current=await post('/api/session',{});}session=current.id;remember(session);window.GameView.restore(current.state);showState(current.state);
 if(current.last){$('speaker').textContent='已保存的局面';$('line').textContent=current.last.proposal.npc;$('narration').textContent=current.last.proposal.narration;$('consequence').textContent=current.last.consequences.join(' ');$('consequence').hidden=false;window.__lastTurn=current.last;}
 ready=serviceReady;$('mode').textContent=current.resumed?'已恢复局面':'可自由说话或行动';$('runtimeDetails').textContent=`请求模型：${health.model}；Uuzu；剩余调用尝试${remaining}。角色动作由同一世界状态与演出协议执行。`;$('saveStatus').textContent='局面保存在本地服务；刷新恢复，重开会另建存档。';report(ready?'你可以说自己的话，也可以先观察现场。':'AI接口不可用，当前场景可查看。',!ready);
}catch(err){ready=false;$('mode').textContent='AI试玩尚未连接';$('accessFeedback').textContent=err.message;report(err.message,true);}updateControls();}
document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>{$('input').value=button.dataset.prompt;$('input').focus();report('可以修改这句话；AI暂停期间保留输入，不发送。');}));
$('inputForm').addEventListener('submit',async event=>{event.preventDefault();if(pending||acting||!ready||remaining<=0)return;const input=$('input').value.trim();if(!input){report('先写下你想说的话或行动。',true);return;}if(recognizing)recognition.stop();pending=true;updateControls();report('对方正在理解你的做法……');
try{const result=await post('/api/turn',{id:session,input});window.__lastTurn=result;showState(result.state);$('mode').textContent='实时AI回应 · 人物正在配合';$('consequence').textContent=result.consequences.join(' ');$('consequence').hidden=false;$('runtimeDetails').textContent=`实际回报型号：${result.model}；${(result.elapsed_ms/1000).toFixed(1)}秒；剩余${remaining}次。回执${result.call_id}。`;window.GameView.perform(result.proposal,result.state);report(`你的意图：“${result.proposal.understanding}”`);
}catch(err){$('mode').textContent='这一轮未完成';report(err.message+' 输入与之前的局面保留。',true);}finally{pending=false;updateControls();}});
document.addEventListener('performance-started',()=>{acting=true;updateControls();});document.addEventListener('performance-ended',()=>{acting=false;$('mode').textContent='可继续说话或行动';updateControls();report(remaining>0?'人物已作出反应；你可以接着尝试。':'这次模型验证额度已用完，场景与局面仍保留。');});
$('reset').addEventListener('click',async()=>{if(pending||acting)return;pending=true;updateControls();try{const reply=await TrialConnection.fetch('/api/health');const health=await reply.json();if(!reply.ok)throw Error(health.error||'试玩连接未完成。');remaining=health.remaining;const current=await post('/api/session',{reset:true});session=current.id;remember(session);await sceneReady;window.GameView.restore(current.state);showState(current.state);ready=health.ready;$('input').value='';$('speaker').textContent='地球治安军征募官';$('line').textContent='签字，你可以留下。你的同行者仍按名单转运。';$('narration').textContent='你们站在柜台外。留下的条件还没有问清。';$('consequence').hidden=true;$('mode').textContent='重新进入局面';window.__lastTurn=null;report('重开局面不会重置模型预算。');}catch(err){report(err.message,true);}finally{pending=false;updateControls();}});
const inspections={application:{title:'治安军申请单',text:'这份申请针对你本人。签字意味着替占领者管理和控制其他地球人；纸上没有同行者免迁的保证。'},order:{title:'强制迁徙令',text:'指示牌要求地球人按名单前往澳大利亚。迁徙不是自愿旅行，征募官也不是中立的移民服务人员。'},side_door:{title:'柜台侧方',text:'侧门附近站着一个人。你尚不知道他的立场，也没有确认那里存在可靠的反抗联系。'},officer:{title:'地球治安军征募官',text:'他是替占领者执行征募的地球人。你可以质问、询问条件，也可以试探。',prompt:'我想问你，留下究竟需要替占领者做什么？'},companion:{title:'你的同行者',text:'他和你站在柜台外。留下和分离，是你们此刻必须面对的困境。',prompt:'我压低声音和同行者商量，我们接下来应该怎么配合？'},contact:{title:'侧门附近的人',text:'你还未确定他是谁。隐蔽联系需要试探，不能在这里公开报名加入反抗军。'}};
function inspect(key){if(pending)return;const item=inspections[key];if(!item)return;$('inspectTitle').textContent=item.title;$('inspectText').textContent=item.text;$('inspectCard').hidden=false;if(item.prompt){$('input').value=item.prompt;report('已写入提问草稿，可以改成自己的话。');}}
document.querySelectorAll('[data-inspect]').forEach(b=>b.addEventListener('click',()=>inspect(b.dataset.inspect)));document.addEventListener('scene-inspect',e=>inspect(e.detail));$('closeInspect').addEventListener('click',()=>{$('inspectCard').hidden=true;});
$('helpButton').addEventListener('click',()=>{$('help').hidden=!$('help').hidden;$('helpButton').setAttribute('aria-expanded',String(!$('help').hidden));});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('help').hidden=true;$('inspectCard').hidden=true;$('helpButton').setAttribute('aria-expanded','false');}});
$('exportAssets').addEventListener('click',()=>{const json=window.GameView.exportJSON(),blob=new Blob([JSON.stringify(json)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='occupation-checkpoint.three.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
if(Recognition){recognition=new Recognition();recognition.lang='zh-CN';recognition.interimResults=true;let prefix='';recognition.onstart=()=>{recognizing=true;$('voice').textContent='结束录音';$('voiceStatus').textContent='正在转写，确认文字后再发送。';};recognition.onresult=e=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript;$('input').value=(prefix+text).slice(0,600);};recognition.onend=()=>{recognizing=false;$('voice').textContent='语音输入';};recognition.onerror=e=>{$('voiceStatus').textContent=({'not-allowed':'麦克风权限未允许。','audio-capture':'未找到麦克风。','network':'语音识别服务不可达。','no-speech':'未识别到语音。'}[e.error]||'语音转写未完成。')+' 可继续输入文字。';};$('voice').addEventListener('click',()=>{if(recognizing){recognition.stop();return;}prefix=$('input').value?$('input').value+' ':'';try{recognition.start();}catch{$('voiceStatus').textContent='语音没有启动，可继续输入文字。';}});
}else{$('voiceStatus').textContent='当前浏览器不支持语音转写。';}
window.GameUI={inspect,debug(){return {pending,acting,session,remaining,ready};}};
$('connectTrial').addEventListener('click',()=>{$('trialAccess').hidden=false;$('invite').focus();});
$('previewScene').addEventListener('click',()=>{$('trialAccess').hidden=true;});
$('accessForm').addEventListener('submit',async e=>{e.preventDefault();if(pending||acting)return;TrialConnection.setInvite($('invite').value);$('connectNow').disabled=true;$('accessFeedback').textContent='正在连接本次试玩……';await connect();$('connectNow').disabled=false;if(ready)$('trialAccess').hidden=true;});
if(!TrialConnection.closed&&TrialConnection.hasInvite){$('trialAccess').hidden=true;connect();}else{updateControls();if(TrialConnection.closed)$('trialAccess').hidden=true;$('mode').textContent='可观察场景 · AI已暂停';$('accessFeedback').textContent=TrialConnection.closed?'实验性Demo v0.02，AI服务暂停；可查看场景和编辑输入。':TrialConnection.configured?'向主办者获取本批试玩口令。':'主办者尚未开放AI服务，场景仍可查看。';}

