const stored=k=>{try{return localStorage.getItem(k)||'';}catch{return '';}},put=(k,v)=>{try{localStorage.setItem(k,v);}catch{}};
let player=stored('mt-trial-v03-player');if(!/^[A-Za-z0-9_-]{24,100}$/.test(player)){player=typeof crypto.randomUUID==='function'?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');put('mt-trial-v03-player',player);}
const normalizeInvite=value=>String(value).normalize('NFKC').replace(/[\s\u200B-\u200D\uFEFF]/g,'').toLowerCase();
let invite='';try{invite=normalizeInvite(sessionStorage.getItem('mt-trial-v03-invite')||'');}catch{}
let config={apiBase:'',status:'host-offline'};try{const res=await fetch('trial-config.json?fresh='+Date.now(),{cache:'no-store'});if(res.ok)config=await res.json();}catch{}
const url=new URL(config.apiBase||location.origin);let valid=/^https:$/.test(url.protocol)&&/^[a-z0-9-]+\.trycloudflare\.com$/.test(url.hostname)&&!url.username&&!url.password&&!url.port&&url.pathname==='/';
if(['127.0.0.1','localhost'].includes(location.hostname)&&(!config.apiBase||url.protocol==='http:'))valid=true;
const base=valid?(config.apiBase||location.origin).replace(/\/$/,''):'';
export const TrialConnection={get configured(){return !!base;},get hasInvite(){return !!invite;},setInvite(value){invite=normalizeInvite(value);try{sessionStorage.setItem('mt-trial-v03-invite',invite);}catch{}},async fetch(route,options={}){if(!base)throw Error('主办者尚未开放本次AI试玩，场景仍可查看。');if(!invite)throw Error('请先输入试玩口令。');if(!/^[0-9a-f]{16}$/.test(invite))throw Error('试玩口令应为16位字母或数字，请只粘贴主办者提供的口令。');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),95000);try{return await fetch(base+route,{...options,signal:controller.signal,headers:{...options.headers,authorization:'Bearer '+invite,'x-player-key':player}});}catch(err){if(err.name==='AbortError')throw Error('等待回应超时，请保留输入，稍后查看存档；不要立即重复提交。');throw Error('主办者的试玩服务未连接。请稍后再试，场景和输入仍保留。');}finally{clearTimeout(timer);}}};
