export const capability={schema:'scene-plan-v1',revision:'R05',primitives:['move_to','face','say','read_notice','wait','jump_counter','leave_counter','play_clip'],actors:['player','officer','companion'],clips:[{"name":"idle_breathe","loop":true,"posture_pre":"standing","posture_post":"standing"},{"name":"walk_in_place","loop":true,"posture_pre":"standing","posture_post":"standing"},{"name":"stop_settle","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"turn_left_90","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"turn_right_90","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"look_left","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"look_right","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"point_forward","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"wave_right","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"reach_forward","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"punch_right","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"push_forward","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"dance_loop","loop":true,"posture_pre":"standing","posture_post":"standing"},{"name":"dodge_back","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"guard_front","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"recoil_front","loop":false,"posture_pre":"standing","posture_post":"standing"},{"name":"crouch_down","loop":false,"posture_pre":"standing","posture_post":"crouched"},{"name":"stand_up","loop":false,"posture_pre":"crouched","posture_post":"standing"}],clip_actor:'player',limits:{steps:8,seconds:6,bounds:[-6,6,-6,8]},unsupported:['pickup','hand_over','hit','force','NPC_animation','fly','generated_animation','toilet','application_receipt','admission']};
export function validatePlan(p){
 p=structuredClone(p);if(Array.isArray(p?.steps))for(const s of p.steps){if(s?.op===undefined&&typeof s?.action==='string')s.op=s.action;else if(s?.action!==undefined&&s.action!==s.op)throw Error('AMBIGUOUS_OPERATION');}
 if(!p||p.schema!==capability.schema||!['allowed','world_forbidden','capability_missing'].includes(p.decision)||typeof p.explanation!=='string'||p.explanation.length>500||!Array.isArray(p.steps)||p.steps.length>8)throw Error('PLAN_SCHEMA_INVALID');
 if(Object.keys(p).some(k=>!['schema','revision','decision','explanation','steps'].includes(k)))throw Error('UNKNOWN_PLAN_FIELD');if(p.revision!==undefined&&p.revision!=='R05')throw Error('CAPABILITY_REVISION_MISMATCH');
 if(p.decision!=='allowed'&&p.steps.length)throw Error('REFUSAL_HAS_ACTIONS');
 for(const s of p.steps){if(!s||!capability.primitives.includes(s.op))throw Error('ENGINE_CAPABILITY_MISSING');
  const fields={move_to:['actor','x','z'],face:['actor','target'],say:['actor','text'],wait:['seconds'],read_notice:[],jump_counter:[],leave_counter:[],play_clip:['actor','clip','params']}[s.op];
  if(Object.keys(s).some(k=>!['op','action',...fields].includes(k)))throw Error('UNKNOWN_OPERATION_FIELD');
  if(s.op==='move_to'&&(s.actor!=='player'||!Number.isFinite(s.x)||!Number.isFinite(s.z)||s.x<-6||s.x>6||s.z<-6||s.z>8))throw Error('WORLD_TARGET_INVALID');
  if(s.op==='face'&&(!capability.actors.includes(s.actor)||!capability.actors.includes(s.target)||s.actor===s.target))throw Error('ACTOR_INVALID');
  if(s.op==='say'&&(!capability.actors.includes(s.actor)||typeof s.text!=='string'||!s.text.trim()||s.text.length>200))throw Error('DIALOGUE_INVALID');
  if(s.op==='wait'&&(!Number.isFinite(s.seconds)||s.seconds<0||s.seconds>6))throw Error('WAIT_INVALID');
  if(s.op==='play_clip'){const c=capability.clips.find(c=>c.name===s.clip),params=s.params??{};if(s.actor!=='player'||!c)throw Error('CLIP_ACTOR_UNSUPPORTED');if(typeof params!=='object'||params===null||Array.isArray(params)||Object.keys(params).some(k=>!['rate','cycles'].includes(k)))throw Error('UNKNOWN_CLIP_PARAMETER');if((params.rate??1)!==1||!Number.isInteger(params.cycles??1)||(params.cycles??1)<1||(params.cycles??1)>4||(!c.loop&&(params.cycles??1)!==1))throw Error('CLIP_PARAMETER_UNVERIFIED');}
 }return p;
}
