import * as T from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {move,canOccupy,clipCamera,advanceBody,recoverCamera,pathTo} from './navigation.mjs';
import {ThreeActionDriver,verifyLibrary} from './action-driver.mjs';
import {ActionDirector} from './director.mjs';
const inputs=await(await fetch('./inputs.json')).json();
const canvas=document.getElementById('scene'),renderer=new T.WebGLRenderer({canvas,antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia("(pointer: coarse)").matches?1:1.25));renderer.shadowMap.enabled=!matchMedia("(pointer: coarse)").matches;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const world=window.SceneAssets.build(T),scene=world.scene,actors=world.actors;
for(const child of [...scene.children])if(!Object.values(actors).some(a=>a.root===child))scene.remove(child);
const design=inputs.contracts.design,layout=inputs.contracts.layout,loader=new GLTFLoader();
if(!layout)throw Error('Stage layout unavailable');
const nav={bounds:layout.bounds,colliders:structuredClone(layout.colliders),radius:design?.player.radius_m??.28,height:design?.player.height_m??1.84};
async function asset(id){const item=inputs.assets[id];if(!item)return null;const b=await(await fetch(item.url)).arrayBuffer(),h=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');if(h!==item.sha256)throw Error(id+' frozen identity mismatch');const g=await loader.parseAsync(b,'');g.scene.traverse(o=>{o.castShadow=true;o.receiveShadow=true;});return g;}
const stageAsset=await asset('stage');if(stageAsset)scene.add(stageAsset.scene);else{for(const c of layout.colliders){if(c.name==='floor'||c.name.startsWith('wall')||c.name.includes('column')||c.name.includes('roof')||c.name==='counter_proxy'){const size=c.max.map((v,i)=>v-c.min[i]),mesh=new T.Mesh(new T.BoxGeometry(...size),new T.MeshStandardMaterial({color:c.name==='counter_proxy'?0x686d65:0x7c8380}));mesh.position.set(...c.max.map((v,i)=>(v+c.min[i])/2));mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);}}}
const lighting=inputs.contracts.lighting,profile=lighting.profiles.bright;renderer.toneMappingExposure=profile.exposure;scene.add(new T.HemisphereLight(lighting.hemisphere.sky,lighting.hemisphere.ground,profile.ambient_intensity));let fixtureCount=0;stageAsset.scene.traverse(o=>{if(o.isLight){o.intensity*=profile.embedded_light_scale;fixtureCount++;o.castShadow=false;}});
const table=nav.colliders.find(c=>c.name==='counter_proxy');if(!table)throw Error('Stage has no counter support');
const top=stageAsset?.scene.getObjectByName('counter_top_proxy');if(top){const bb=new T.Box3().setFromObject(top);table.max[1]=bb.max.y;table.min[0]=bb.min.x;table.max[0]=bb.max.x;table.min[2]=bb.min.z;table.max[2]=bb.max.z;}
actors.officer.root.position.set(...(design?.stage.adapter_overrides?.officer_proxy??[-.25,0,-1.18]));
actors.officer.base={x:actors.officer.root.position.x,z:actors.officer.root.position.z,yaw:0};
const officerAsset=await asset('officer');actors.officer.body.visible=false;actors.officer.root.rotation.y=0;actors.officer.root.add(officerAsset.scene);actors.officer.staticCandidate=true;
scene.updateMatrixWorld(true);for(const [id,a]of Object.entries(actors)){if(id==='player')continue;const p=a.root.position;if(id==='officer'){const bb=new T.Box3().setFromObject(officerAsset.scene);nav.colliders.push({name:'actor-'+id,min:bb.min.toArray(),max:bb.max.toArray(),character:true,camera:true});}else nav.colliders.push({name:'actor-'+id,min:[p.x-.29,0,p.z-.29],max:[p.x+.29,1.84,p.z+.29],character:true,camera:true});}
const paper=world.paper,paperAsset=await asset('paper');paper.clear();paper.add(paperAsset.scene);scene.add(paper);paper.position.set(-.90,0,.10);const paperBounds=new T.Box3().setFromObject(paper);paper.position.y=table.max[1]+.002-paperBounds.min.y;paper.userData.owner='counter';paper.userData.binding='Native static rest only; no delivery/receipt animation';
const stagePaperProxy=stageAsset.scene.getObjectByName('paper_proxy');if(stagePaperProxy)stagePaperProxy.visible=false;
const player=actors.player,playerAsset=await asset('player'),contract=inputs.contracts.animation;
const legacyJumpAsset=await asset('jump');playerAsset.animations.push(legacyJumpAsset.animations.find(c=>c.name==='jump_to_table'));const libraryContract=inputs.contracts.action_library,libraryVerification=await verifyLibrary(playerAsset,libraryContract);
let mixer,walkAction,jumpAction,rootBone,feet=[],native,walkClock=0,heldFinal=false;
if(playerAsset&&contract){
 player.body.visible=false;player.root.rotation.y=0;player.root.add(playerAsset.scene);mixer=new T.AnimationMixer(playerAsset.scene);rootBone=playerAsset.scene.getObjectByName('root');feet=['foot_L','foot_R'].map(n=>playerAsset.scene.getObjectByName(n));
 const walk=playerAsset.animations.find(a=>a.name==='walk_in_place'),jump=playerAsset.animations.find(a=>a.name==='jump_to_table');
 if(!rootBone||feet.some(f=>!f)||!jump||!walk)throw Error('Native motion contract lacks actual nodes/clips');
 if(Math.abs(contract.table.top_y_m-table.max[1])>contract.sole.contact_tolerance_m)throw Error('Native tabletop contract mismatch');
 walkAction=mixer.clipAction(walk);jumpAction=mixer.clipAction(jump);jumpAction.setLoop(T.LoopOnce,1);jumpAction.clampWhenFinished=true;
 const finalDelta=contract.clips.find(c=>c.name==='jump_to_table').end_runtime;
 if(Math.abs(finalDelta[1]-table.max[1])<.015){native={duration:jump.duration,walk_speed:contract.clips.find(c=>c.name==='walk_in_place').speed_mps,start_z:(table.min[2]+table.max[2])/2-finalDelta[2],sample(time,launch){heldFinal=false;walkAction.stop();player.root.position.set(launch.x,launch.y,launch.z);player.root.rotation.y=0;jumpAction.reset().play();jumpAction.time=Math.min(jump.duration,time);jumpAction.paused=true;mixer.update(0);scene.updateMatrixWorld(true);const actual=rootBone.getWorldPosition(new T.Vector3()),sole=Math.min(...feet.map(f=>f.getWorldPosition(new T.Vector3()).y-contract.sole.ankle_above_sole_m));return {position:{x:actual.x,y:actual.y,z:actual.z},feet_y:sole,phase:time<1.2?'approach':time<1.65?'crouch':time<1.85?'takeoff':time<2.6?'airborne':'landing'};}};}
}
let position={x:layout.anchors.player_start[0],y:0,z:layout.anchors.player_start[2]},yaw=design?.camera.orbit_yaw_rad??0,pitch=design?.camera.orbit_pitch_rad??.08,distance=design?.camera.distance_m??2.8,shoulder=1;
if(!native)throw Error('Verified native jump binding unavailable; this asset-intake candidate cannot use a proxy success');
function assetEvidence(){scene.updateMatrixWorld(true);const bb=new T.Box3().setFromObject(paper),officerBox=new T.Box3().setFromObject(officerAsset.scene);return {action_library_revision:libraryContract.revision,action_library_clip_count:libraryContract.clips.length,lighting_profile:'bright',fixture_count:fixtureCount,officer_native:true,paper_native:true,stage_paper_proxy_hidden:!stagePaperProxy?.visible,officer_clips:officerAsset.animations.map(c=>c.name),officer_bounds:{min:officerBox.min.toArray(),max:officerBox.max.toArray()},paper_bounds:{min:bb.min.toArray(),max:bb.max.toArray()},paper_bottom_gap_m:bb.min.y-table.max[1],paper_owner:paper.userData.owner,contract_height_m:contract.height_m,walk_speed_ratio:(design.player.walk_speed_mps/contract.clips.find(c=>c.name==='walk_in_place').speed_mps),preserved_placeholders:['companion','environment crowd'],geometry_counts:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles},layout_vs_mesh_table:{declared:layout.colliders.find(c=>c.name==='counter_proxy').max[1],actual:table.max[1]}};}
const camera=new T.PerspectiveCamera(design?.camera.fov_deg??48,1,.05,60),keys=new Set(),director=new ActionDirector(nav,table,native),samples=[];
let clipExecution=null,worldVersion=0,recoveryStable=0;
let owner='EXPLORE',last=performance.now(),cameraData={},moving=false,inspection=false,dragging=false,previousOrbit=null,settledState=false,verticalSpeed=0,autoLeave=false,returnRemaining=0,counterEligible=false,plannedMove=null,suspended=false,activePointer=null,lastClearCamera=null;
const dispatch=(name,detail)=>document.dispatchEvent(new CustomEvent(name,{detail}));
function setOwner(value){owner=value;keys.clear();dragging=false;moving=false;if(activePointer!==null&&canvas.hasPointerCapture(activePointer))canvas.releasePointerCapture(activePointer);activePointer=null;}

// Conservative swept per-mesh boxes use CPU-skinned vertices, including hands/head.
// Only authored 1x playback is enabled; no contact marker creates a gameplay hit.
const skinMeshes=[];playerAsset.scene.traverse(o=>{if(o.isMesh)skinMeshes.push(o);});
let lastEnvelopes=null,recoveryReason=null;const clipSamples=[];
function bodyEnvelopes(){scene.updateMatrixWorld(true);for(const o of skinMeshes)if(o.isSkinnedMesh)o.skeleton.update();return skinMeshes.map(o=>{const box=new T.Box3(),v=new T.Vector3();for(let i=0;i<o.geometry.attributes.position.count;i++){o.getVertexPosition(i,v);v.applyMatrix4(o.matrixWorld);box.expandByPoint(v);}return box;});}
function supportedFeet(){scene.updateMatrixWorld(true);return feet.every(f=>{const p=f.getWorldPosition(new T.Vector3());return Math.abs(p.y-contract.sole.ankle_above_sole_m)<=contract.sole.contact_tolerance_m&&p.x>=nav.bounds[0]&&p.x<=nav.bounds[1]&&p.z>=nav.bounds[2]&&p.z<=nav.bounds[3];});}
function sweepBody(){const boxes=bodyEnvelopes(),old=lastEnvelopes??boxes;for(let i=0;i<boxes.length;i++){const b=boxes[i].clone().union(old[i]);if(b.min.x<nav.bounds[0]||b.max.x>nav.bounds[1]||b.min.z<nav.bounds[2]||b.max.z>nav.bounds[3])return {ok:false,reason:'BODY_OUT_OF_WORLD'};if(b.min.y<-.006)return {ok:false,reason:'BODY_BELOW_FLOOR'};for(const c of nav.colliders){if(c.character===false||c.max[1]<=.001)continue;const shrink=.003;if(b.max.x>c.min[0]+shrink&&b.min.x<c.max[0]-shrink&&b.max.y>c.min[1]+shrink&&b.min.y<c.max[1]-shrink&&b.max.z>c.min[2]+shrink&&b.min.z<c.max[2]-shrink)return {ok:false,reason:'BODY_SWEEP_BLOCKED:'+c.name};}}lastEnvelopes=boxes;return {ok:true};}
const actionDriver=new ThreeActionDriver({THREE:T,asset:playerAsset,actorRoot:player.root,contract:libraryContract,verification:libraryVerification,mixer,
 authorize({phase,step,context}){if(step.actor!=='player'||context.world_version!==worldVersion)return {ok:false,reason:'STALE_WORLD_OR_ACTOR'};if(owner!=='ACTION')return {ok:false,reason:'ACTION_OWNER_LOST'};if(phase==='start'){if(position.y>.005||!supportedFeet())return {ok:false,reason:'SUPPORTED_FLOOR_REQUIRED'};lastEnvelopes=bodyEnvelopes();if(!sweepBody().ok)return {ok:false,reason:'BODY_START_BLOCKED'};}return {ok:true};},sweep:sweepBody,emit(event){dispatch('clip-observation',event);}});
function tickClip(dt){
 const execution=clipExecution;if(!execution)return;
 if(actionDriver.state==='PLAYING')actionDriver.tick(dt);
 let actual=rootBone.getWorldPosition(new T.Vector3());position={x:actual.x,y:actual.y,z:actual.z};
 const state=actionDriver.state;
 if(state==='RECOVERY_REQUIRED'||state==='CANCEL_PENDING'){
  const x=actionDriver.active;execution.recovering=true;recoveryReason??=actionDriver.events.at(-1)?.reason??'EXECUTION_CANCELLED';
  // Reverse along the actually accepted clip path to its supported initial pose.
  // Collision and sole support are observed again; never restore root by teleport.
  const previous=actionDriver.snapshot(),oldTime=x.time,next=Math.max(0,x.time-dt);
  x.a.time=next%x.c.duration_s;x.a.paused=true;mixer.update(0);actionDriver.refresh();
  if(sweepBody().ok){x.time=next;}else{actionDriver.restore(previous);x.a.time=oldTime%x.c.duration_s;}
  if(x.time===0&&supportedFeet())recoveryStable+=dt;else recoveryStable=0;
  if(recoveryStable>=.25){actionDriver.resolveRecovery({supported:true,settled:true,posture:x.c.posture_pre,reason:recoveryReason});const done=execution,endedReason=state==='CANCEL_PENDING'?'EXECUTION_CANCELLED':recoveryReason;clipExecution=null;recoveryReason=null;lastEnvelopes=null;actual=rootBone.getWorldPosition(new T.Vector3());position={x:actual.x,y:actual.y,z:actual.z};setOwner(suspended?'SUSPENDED':'EXPLORE');done.resolve({ok:false,reason:endedReason??'EXECUTION_INTERRUPTED',actual_pose_preserved:true});return;}
 }else if(state==='IDLE'){
  if(supportedFeet())recoveryStable+=dt;else recoveryStable=0;
  if(recoveryStable>=.25){const done=execution;clipExecution=null;lastEnvelopes=null;setOwner(suspended?'SUSPENDED':'EXPLORE');done.resolve({ok:true,clip:actionDriver.currentStep.clip,posture:actionDriver.posture,worldSuccess:false,supported_stable_s:recoveryStable});return;}
 }
 actual=rootBone.getWorldPosition(new T.Vector3());position={x:actual.x,y:actual.y,z:actual.z};clipSamples.push({clip:actionDriver.currentStep.clip,state:actionDriver.state,position:{...position},feet_y:actualFeet(),supported:supportedFeet()});if(clipSamples.length>90)clipSamples.shift();
}

function actualFeet(){scene.updateMatrixWorld(true);return feet.length?Math.min(...feet.map(f=>f.getWorldPosition(new T.Vector3()).y-.1)):position.y;}
function transferNative(){if(!native||!rootBone)return;player.root.position.set(position.x,position.y,position.z);rootBone.position.set(0,0,0);heldFinal=position.y>.2;}
function walkPose(dt,velocity){
 if(clipExecution||actionDriver.posture==='crouched')return;
 if(mixer){if(heldFinal){jumpAction.stop();rootBone.position.set(0,0,0);heldFinal=false;}if(velocity>.02){jumpAction.stop();walkAction.play();walkAction.paused=false;mixer.update(dt*velocity/(native?.walk_speed??.76));}else{walkAction.stop();rootBone.position.set(0,0,0);}return;}
 walkClock+=dt*8;player.legs.forEach((leg,i)=>leg.rotation.x=velocity>.02?Math.sin(walkClock+i*Math.PI)*.34:0);player.arms.forEach((limb,i)=>limb.arm.rotation.x=velocity>.02?-Math.sin(walkClock+i*Math.PI)*.2:0);
}
function solveCamera(dt){
 let pivot={x:position.x,y:position.y+(design?.camera.pivot_height_m??1.42),z:position.z},desired;
 if(inspection){pivot={x:paper.position.x,y:table.max[1]+.26,z:paper.position.z};desired={x:paper.position.x+.55,y:1.84,z:1.22};}
 else{const offset=shoulder*(design?.camera.shoulder_offset_m??.48);desired={x:pivot.x+Math.sin(yaw)*distance+Math.cos(yaw)*offset,y:pivot.y+Math.sin(pitch)*distance,z:pivot.z+Math.cos(yaw)*distance-Math.sin(yaw)*offset};}
 let clipped=recoverCamera(pivot,desired,lastClearCamera,nav.colliders,design?.camera.collision_radius_m??.22,dt,matchMedia('(prefers-reduced-motion: reduce)').matches),fallback=false;if(clipped.fraction<=0&&lastClearCamera){const checked=clipCamera(pivot,lastClearCamera,nav.colliders,design?.camera.collision_radius_m??.22);if(checked.fraction>.98){clipped={...lastClearCamera,blocker:clipped.blocker};fallback=true;}}else if(clipped.fraction>0)lastClearCamera={...clipped,pivot:{...pivot}};camera.position.set(clipped.x,clipped.y,clipped.z);camera.lookAt(pivot.x,pivot.y,pivot.z);cameraData={pivot,desired,actual:{x:clipped.x,y:clipped.y,z:clipped.z},fraction:clipped.fraction,blocker:clipped.blocker,fallback_last_clear:fallback,mode:inspection?'INSPECT':'SHOULDER'};
 // Only the controlled actor is faded when the camera retracts close to its body.
 const fade=Math.hypot(clipped.x-position.x,clipped.z-position.z)<.7;player.root.visible=!fade;
}
function resize(){renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);resize();
function tick(now){const dt=Math.min(.05,(now-last)/1000);last=now;const before={...position};
 if(clipExecution){tickClip(dt);}else if(!director.done){const value=director.tick(dt,position);position=value.position;if(value.phase.startsWith('native_')){}else if(native&&value.phase==='stable'){transferNative();}else{const dx=position.x-before.x,dz=position.z-before.z;if(Math.hypot(dx,dz)>.001)player.root.rotation.y=Math.atan2(-dx,-dz);player.root.position.set(position.x,position.y,position.z);walkPose(dt,Math.hypot(dx,dz)/dt);}
  const snapshot={phase:value.phase,position:{...position},feet_y:actualFeet(),tabletop_y:table.max[1],time:now};if(samples.at(-1)?.phase!==value.phase||samples.length%8===0){samples.push(snapshot);if(samples.length>180)samples.shift();}dispatch('action-progress',snapshot);
  if(value.done){transferNative();setOwner(suspended?'SUSPENDED':'EXPLORE');dispatch('action-finished',{success:value.success,reason:value.reason,events:director.events,phases:director.phaseEvents,cancelled:director.cancelRequested||value.phase==='cancelled',position:{...position},feet_y:actualFeet()});}
 }else if(owner==='EXPLORE'||plannedMove||autoLeave){if(plannedMove){const goal=plannedMove.path[plannedMove.index],dx=goal.x-position.x,dz=goal.z-position.z,d=Math.hypot(dx,dz);if(d<.04){plannedMove.index++;if(plannedMove.index>=plannedMove.path.length){const complete=plannedMove;plannedMove=null;setOwner("EXPLORE");complete.resolve({ok:true,position:{...position}});}}else{const next=advanceBody(position,{x:dx/d*Math.min(d,1.55*dt),z:dz/d*Math.min(d,1.55*dt)},nav,dt,verticalSpeed);if(Math.hypot(next.position.x-position.x,next.position.z-position.z)<1e-6){const blocked=plannedMove;plannedMove=null;setOwner("EXPLORE");blocked.resolve({ok:false,reason:'WORLD_PATH_BLOCKED'});}else{position=next.position;verticalSpeed=next.verticalSpeed;player.root.rotation.y=Math.atan2(-dx,-dz);}}}let f=Number(keys.has('w'))-Number(keys.has('s')),r=Number(keys.has('d'))-Number(keys.has('a')),n=Math.hypot(f,r);if(autoLeave){f=-1;r=0;n=1;}if(actionDriver.posture!=='standing'){n=0;f=r=0;}if(n){f/=n;r/=n;const speed=design?.player.walk_speed_mps??1.55;const step=advanceBody(position,{x:autoLeave?0:(-Math.sin(yaw)*f+Math.cos(yaw)*r)*speed*dt,z:autoLeave?speed*dt:(-Math.cos(yaw)*f-Math.sin(yaw)*r)*speed*dt},nav,dt,verticalSpeed);position=step.position;verticalSpeed=step.verticalSpeed;const dx=position.x-before.x,dz=position.z-before.z;if(Math.hypot(dx,dz)>.001)player.root.rotation.y=Math.atan2(-dx,-dz);}
  if(!n){const step=advanceBody(position,{x:0,z:0},nav,dt,verticalSpeed);position=step.position;verticalSpeed=step.verticalSpeed;}if(before.y>.005&&position.y<=.005){autoLeave=false;setOwner('EXPLORE');dispatch('body-floor-settled',{position:'floor',proof:{stable:true,feet_y:position.y,tabletop_y:0}});}player.root.position.set(position.x,position.y,position.z);walkPose(dt,Math.hypot(position.x-before.x,position.z-before.z)/Math.max(dt,.001));
 }else if(heldFinal)transferNative();
 if(owner==='RETURNING'){returnRemaining-=dt;if(returnRemaining<=0)setOwner(suspended?'SUSPENDED':'EXPLORE');}moving=Math.hypot(position.x-before.x,position.z-before.z)>.001;solveCamera(dt);renderer.render(scene,camera);dispatch('scene-context',{nearCounter:nearCounter(),owner,position:{...position}});requestAnimationFrame(tick);
}
function nearCounter(){const anchor=design?.interaction.counter.anchor??[-.25,0,.75],d=Math.hypot(position.x-anchor[0],position.z-anchor[2]);const los=clipCamera({x:position.x,y:1.4,z:position.z},{x:anchor[0],y:1.4,z:anchor[2]},nav.colliders.filter(c=>c.name!=='counter_proxy'),0);const radius=counterEligible?(design?.interaction.counter.exit_radius_m??1.45):(design?.interaction.counter.enter_radius_m??1.25);counterEligible=d<=radius&&los.fraction>.98&&position.y<.2;return counterEligible;}
canvas.addEventListener('keydown',e=>{if(owner!=='EXPLORE')return;const k=e.key.toLowerCase();if('wasd'.includes(k)&&k.length===1){keys.add(k);e.preventDefault();}if(k==='q'){shoulder*=-1;e.preventDefault();}if(k==='e'&&nearCounter()){dispatch('request-inspect');e.preventDefault();}if(k==='enter'){dispatch('request-compose');e.preventDefault();}});
canvas.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.focus();if((e.button===2||e.pointerType==='touch')&&owner==='EXPLORE'){dragging=true;activePointer=e.pointerId;canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(dragging){yaw-=e.movementX*.005;pitch=Math.max(-.25,Math.min(.7,pitch+e.movementY*.004));}});canvas.addEventListener('pointerup',()=>{dragging=false;if(activePointer!==null&&canvas.hasPointerCapture(activePointer))canvas.releasePointerCapture(activePointer);activePointer=null;});canvas.addEventListener('wheel',e=>{if(owner==='EXPLORE'){distance=Math.max(.65,Math.min(4.2,distance+e.deltaY*.002));e.preventDefault();}},{passive:false});
function suspend(){if(clipExecution)actionDriver.cancel();if(plannedMove){plannedMove.resolve({ok:false,reason:"EXECUTION_SUSPENDED"});plannedMove=null;}suspended=true;autoLeave=false;if(!director.done)director.cancel();setOwner('SUSPENDED');dispatch('scene-suspended');}window.addEventListener('blur',suspend);document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});
export const view={
 inputs,nav,table,nativeMotion:!!native,setOwner,
 setWorldVersion(v){worldVersion=v;},
 playClip(step,context){if(owner!=='EXPLORE'||clipExecution||!director.done)return Promise.resolve({ok:false,reason:'OWNER_BUSY'});setOwner('ACTION');return new Promise(resolve=>{try{actionDriver.play({primitive:'play_clip',actor:step.actor,clip:step.clip,params:step.params},context);clipExecution={resolve,context,recovering:false};recoveryStable=0;}catch(e){setOwner('EXPLORE');resolve({ok:false,reason:e.message});}});},
 touchMove(key,pressed){if(owner!=='EXPLORE')return;pressed?keys.add(key):keys.delete(key);},
 face(actor,target){const a=actors[actor],b=actors[target];if(!a||!b)return {ok:false,reason:'ENGINE_CAPABILITY_MISSING'};const dx=b.root.position.x-a.root.position.x,dz=b.root.position.z-a.root.position.z;a.root.rotation.y=actor==='player'?Math.atan2(-dx,-dz):Math.atan2(dx,dz);return {ok:true};},
 moveTo(x,z){if(actionDriver.posture!=='standing')return Promise.resolve({ok:false,reason:'POSTURE_PRECONDITION'});if(owner!=='EXPLORE'||plannedMove||position.y>.2)return Promise.resolve({ok:false,reason:position.y>.2?'WORLD_SUPPORT_MISMATCH':'OWNER_BUSY'});const path=pathTo(position,{x,y:position.y,z},nav);if(!path.length)return Promise.resolve({ok:false,reason:'WORLD_PATH_BLOCKED'});setOwner('ACTION');return new Promise(resolve=>{plannedMove={path,index:0,resolve};});},
 resume(){suspended=false;setOwner('EXPLORE');canvas.focus();},
 inspect(){previousOrbit={yaw,pitch,distance,shoulder};inspection=true;setOwner('INSPECT');},
 return(){inspection=false;if(previousOrbit){({yaw,pitch,distance,shoulder}=previousOrbit);previousOrbit=null;}returnRemaining=matchMedia('(prefers-reduced-motion: reduce)').matches?0:.35;setOwner(suspended?'SUSPENDED':returnRemaining?'RETURNING':'EXPLORE');canvas.focus();},
 leaveTable(){if(owner!=='EXPLORE'||position.y<.2)return {ok:false,reason:'当前不在可离开的台面'};setOwner('ACTION');autoLeave=true;return {ok:true};},
 start(intent){if(actionDriver.posture!=='standing')return {ok:false,reason:'POSTURE_PRECONDITION'};if(owner!=='EXPLORE')return {ok:false,reason:'OWNER_BUSY'};const result=director.start(position,intent);if(result.ok){heldFinal=false;settledState=false;verticalSpeed=0;setOwner('ACTION');}return result;},
 cancel(){if(clipExecution){actionDriver.cancel();return 'SUPPORTED_RECOVERY_PENDING';}if(plannedMove){plannedMove.resolve({ok:false,reason:'EXECUTION_CANCELLED'});plannedMove=null;setOwner('EXPLORE');return 'CANCELLED';}if(autoLeave){autoLeave=false;setOwner('EXPLORE');return 'CANCELLED';}const result=director.cancel();if(director.done){transferNative();setOwner(suspended?'SUSPENDED':'EXPLORE');canvas.focus();}return result;},
 debug(){return {position:{...position},posture:actionDriver.posture,clip_state:actionDriver.state,clip_events:actionDriver.events.slice(-30),clip_samples:clipSamples.slice(-12),feet_y:actualFeet(),owner,moving,phase:director.phase,done:director.done&&!autoLeave&&!plannedMove&&!clipExecution,success:director.success,events:director.events,phase_events:director.phaseEvents,samples:[...samples],camera:cameraData,near_counter:nearCounter(),native_motion:!!native,stage_native:!!stageAsset,tabletop_y:table.max[1],can_occupy:canOccupy(position,nav),asset_identities:inputs.assets,input_identities:inputs.identities,clips:playerAsset?.animations.map(c=>c.name)??[]};}
};
const originalDebug=view.debug;view.debug=()=>({...originalDebug(),native_assets:assetEvidence()});window.SceneEngineering=view;player.root.position.set(position.x,0,position.z);requestAnimationFrame(tick);
